zpb_sites_bn:
    resource: "@ZPBSitesBNBundle/Resources/config/routing.yml"
    prefix:   /
    host: "maket.beauval-nature.com"

zpb_admin_common:
    resource: "@ZPBAdminCommonBundle/Resources/config/routing.yml"
    prefix:   /
    host: "maket.admin.zooparc.com"

zpb_sites_zoo:
    resource: "@ZPBSitesZooBundle/Resources/config/routing.yml"
    prefix:   /
    host: "maket.zoobeauval.com"

