zpb_sites_pro_homepage:
    path:     /
    defaults: { _controller: ZPBSitesProBundle:Index:index }

zpb_sites_pro_pro_homepage:
    path:     /pro
    defaults: { _controller: ZPBSitesProBundle:Pro:index }
