parameters:
#    zpb_sites_scolaires.example.class: ZPB\Sites\ScolairesBundle\Example

services:
#    zpb_sites_scolaires.example:
#        class: %zpb_sites_scolaires.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
